import { AuthEventReason, AuthEventType } from "@orelia/common";
import type { AuditLogEntryResponse, AuthEventResponse } from "@orelia/common";

// Local-state mock data for the pre-backend UI review pass (mock-first rule,
// feature-development-guideline.md #1). Deliberately covers every `changes`
// shape and edge case called out in spec-activity-log.md's I/O matrix:
// flat snapshot, field diff, boolean flag, id-array delta, join-table rows,
// an unmapped entity_type, a NULL changes payload, a dangling actor, and a
// platform (act-as-tenant) actor. Deleted once real API wiring lands.
export const MOCK_AUDIT_ENTRIES: AuditLogEntryResponse[] = [
  {
    id: "a1",
    occurredAt: "2026-08-02T09:14:00.000Z",
    action: "insert",
    entityType: "user",
    entityId: "u1",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: { username: "jane.doe", displayName: "Jane Doe", status: "active" },
  },
  {
    id: "a2",
    occurredAt: "2026-08-02T08:55:00.000Z",
    action: "update",
    entityType: "deal",
    entityId: "d1",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: {
      name: { old: "Acme Renewal", new: "Acme Renewal 2026" },
      estimatedValue: { old: 12000, new: 18500 },
    },
  },
  {
    id: "a3",
    occurredAt: "2026-08-02T08:40:00.000Z",
    action: "update",
    entityType: "user",
    entityId: "u2",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: { passwordReset: true, mustChangePassword: true, lockoutCleared: true },
  },
  {
    id: "a4",
    occurredAt: "2026-08-02T08:20:00.000Z",
    action: "update",
    entityType: "user",
    entityId: "u1",
    actorId: "u1",
    actorName: "Jane Doe",
    actorIsPlatform: false,
    changes: { passwordSelfChanged: true },
  },
  {
    id: "a5",
    occurredAt: "2026-08-02T07:58:00.000Z",
    action: "update",
    entityType: "user",
    entityId: "u3",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: { addedRoleIds: ["role-sales", "role-support"] },
  },
  {
    id: "a6",
    occurredAt: "2026-08-02T07:30:00.000Z",
    action: "update",
    entityType: "rbac_role",
    entityId: "role-sales",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: { resourceIds: { old: ["deals:view", "deals:create"], new: ["deals:view", "deals:create", "deals:update"] } },
  },
  {
    id: "a7",
    occurredAt: "2026-08-02T07:05:00.000Z",
    action: "delete",
    entityType: "deal",
    entityId: "d9",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: { name: "Stale Prospect Co.", dealCode: "DEAL-00042" },
  },
  {
    id: "a8",
    occurredAt: "2026-08-02T06:40:00.000Z",
    action: "insert",
    entityType: "deal_partner",
    entityId: "join-1",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: { dealId: "d1", companyId: "c8" },
  },
  {
    id: "a9",
    occurredAt: "2026-08-01T23:10:00.000Z",
    action: "delete",
    entityType: "relationship_company_contact_map",
    entityId: "join-2",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: { relationshipTypeId: "rt1", companyId: "c3" },
  },
  {
    id: "a10",
    occurredAt: "2026-08-01T20:00:00.000Z",
    action: "update",
    entityType: "deal",
    entityId: "d1",
    actorId: null,
    actorName: null,
    actorIsPlatform: false,
    changes: { status: { old: "open", new: "won" } },
  },
  {
    id: "a11",
    occurredAt: "2026-08-01T18:15:00.000Z",
    action: "update",
    entityType: "tenant",
    entityId: "t1",
    actorId: "sysadmin1",
    actorName: null,
    actorIsPlatform: true,
    changes: { status: { old: "trial", new: "active" } },
  },
  {
    id: "a12",
    occurredAt: "2026-08-01T15:30:00.000Z",
    action: "delete",
    entityType: "deal_tender_detail",
    entityId: "td1",
    actorId: "admin1",
    actorName: "Nimal Perera",
    actorIsPlatform: false,
    changes: null,
  },
];

export const MOCK_AUTH_EVENTS: AuthEventResponse[] = [
  {
    id: "e1",
    occurredAt: "2026-08-02T09:00:12.000Z",
    eventType: AuthEventType.LoginSucceeded,
    reason: null,
    userId: "admin1",
    usernameAttempted: "nimal.perera",
    ipAddress: "10.20.0.14",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0",
  },
  {
    id: "e2",
    occurredAt: "2026-08-02T08:58:40.000Z",
    eventType: AuthEventType.LoginFailed,
    reason: AuthEventReason.BadPassword,
    userId: "admin1",
    usernameAttempted: "nimal.perera",
    ipAddress: "10.20.0.14",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0",
  },
  {
    id: "e3",
    occurredAt: "2026-08-02T08:45:02.000Z",
    eventType: AuthEventType.AccountLocked,
    reason: AuthEventReason.LockedOut,
    userId: "u5",
    usernameAttempted: "disable.target.test",
    ipAddress: "203.0.113.7",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X)",
  },
  {
    id: "e4",
    occurredAt: "2026-08-02T08:44:58.000Z",
    eventType: AuthEventType.LoginFailed,
    reason: AuthEventReason.LockedOut,
    userId: "u5",
    usernameAttempted: "disable.target.test",
    ipAddress: "203.0.113.7",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X)",
  },
  {
    id: "e5",
    occurredAt: "2026-08-02T02:12:00.000Z",
    eventType: AuthEventType.LoginFailed,
    reason: AuthEventReason.UnknownUser,
    userId: null,
    usernameAttempted: "admin'--",
    ipAddress: "198.51.100.23",
    userAgent: "curl/8.4.0",
  },
  {
    id: "e6",
    occurredAt: "2026-08-01T19:20:00.000Z",
    eventType: AuthEventType.Logout,
    reason: null,
    userId: "admin1",
    usernameAttempted: "nimal.perera",
    ipAddress: "10.20.0.14",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0",
  },
];
